DELETE http://localhost:8080/jobs/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInVzZXJJRCI6NywiaXNfYWRtaW4iOnRydWUsImV4cCI6MTczNTMzNzkwMn0.PvyHTqO8IzboQRWOsfdTfUoh9pUU78k9-xH_fRtV1yY