PUT http://localhost:8080/users/change-password
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInVzZXJJRCI6NywiaXNfYWRtaW4iOnRydWUsImV4cCI6MTczMjM5OTY3Mn0.556A8yOuUJYGhP3pZCRQ_AlLj-pd9uivm1MEA2moJYU

{
    "current_password": "password123",
    "new_password": "Test@123"
}